-- Doctor reports (one row per appointment)
create table if not exists doctor_reports (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid unique not null references appointments(id) on delete cascade,
  patient_id uuid not null references profiles(id) on delete cascade,
  doctor_id uuid references profiles(id),

  report_date date,
  company text,
  sa_no text,
  status text,

  health_history text,
  present_illness text,
  medications text,
  allergies_notes text,
  operations text,

  smoker boolean,
  packs_per_day text,
  alcohol_drinker boolean,
  alcohol_years text,

  physical_skin text,
  physical_head text,
  physical_ears text,
  physical_eyes text,
  physical_nose text,
  physical_neck_throat text,
  physical_heart text,
  physical_chest_lungs text,
  physical_breast text,
  physical_abdomen text,
  physical_anal_inguinal text,
  physical_back text,
  physical_extremities text,
  physical_others text,

  bp_systolic text,
  bp_diastolic text,
  pr text,
  rr text,
  temp_c text,

  vision_wo_od text,
  vision_wo_os text,
  vision_wo_ou text,
  vision_w_od text,
  vision_w_os text,
  vision_w_ou text,
  vision_near_od text,
  vision_near_os text,
  vision_near_ou text,

  ishihara_normal boolean,
  ishihara_defective boolean,

  ob_lmp text,
  ob_score text,
  ob_interval text,
  ob_duration text,
  ob_dysmenorrhea text,

  dental_oral_prophylaxis text,
  dental_fillings text,
  dental_extraction text,
  dental_others text,
  dental_attending text,

  lab_hematology_result text,
  lab_hematology_findings text,
  lab_urinalysis_result text,
  lab_urinalysis_findings text,
  lab_fecalysis_result text,
  lab_fecalysis_findings text,
  lab_chest_xray_result text,
  lab_chest_xray_findings text,
  lab_ecg_result text,
  lab_ecg_findings text,
  lab_psycho_test_result text,
  lab_psycho_test_findings text,
  lab_hbsag_result text,
  lab_hbsag_findings text,
  lab_pregnancy_test_result text,
  lab_pregnancy_test_findings text,
  lab_blood_type_result text,
  lab_blood_type_findings text,
  lab_drug_test_result text,
  lab_drug_test_findings text,

  evaluation text,
  remarks text,
  recommendations text,

  mh_allergies boolean,
  mh_asthma boolean,
  mh_chickenpox boolean,
  mh_diabetes boolean,
  mh_epilepsy boolean,
  mh_german_measles boolean,
  mh_measles boolean,
  mh_cancer boolean,
  mh_hernia boolean,
  mh_kidney_problem boolean,
  mh_thyroid_problem boolean,
  mh_gastritis boolean,
  mh_blood_problem boolean,
  mh_anemia_bleeding_clotting boolean,
  mh_heart_disease boolean,
  mh_hepatitis boolean,
  mh_hypertension boolean,
  mh_ulcers boolean,
  mh_ptb boolean,
  mh_vertigo boolean,
  mh_psych_disorder boolean,

  height_ft text,
  height_in text,
  weight_lbs text,
  examining_physician text,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
